server.port=3000
server.ssl.bundle=server
spring.ssl.bundle.pem.server.keystore.certificate=file:certs/localhost.pem
spring.ssl.bundle.pem.server.keystore.private-key=file:certs/localhost.key
spring.ssl.bundle.pem.server.truststore.certificate=file:certs/root-ca.pem
spring.web.resources.static-locations=file:auth-frontend/ui/dist/,classpath:/static/
auth.backend.base-url=https://localhost:8443
