pcpitman.auth {
  kms-alias = "alias/auth-password"

  dynamodb {
    table-name = "auth-test"
    read-capacity-units = 5
    write-capacity-units = 5
  }

  ses {
    from-address = "no-reply@pcpitman.com"
    default-validation-url-base = "https://localhost:3000/validate-email"
  }

  redis {
    uri = "redis://localhost:6379"
  }

  session {
    ttl-seconds = 3600
  }
}

atlas.pekko {
  api-endpoints = [
    "com.netflix.atlas.pekko.ConfigApi",
    "com.netflix.atlas.pekko.HealthcheckApi",
    "com.pcpitman.auth.AuthApi"
  ]

  ports = [
    {
      port = 8443
      secure = true
      context-factory = "com.pcpitman.auth.PemConnectionContextFactory"
      ssl-config {
        cert-path = "certs/localhost.pem"
        key-path = "certs/localhost.key"
        ca-cert-path = "certs/root-ca.pem"
      }
    }
  ]
}
