pcpitman.auth {
  kms-alias = "alias/auth-password"

  dynamodb {
    table-name = "auth-user"
    read-capacity-units = 1
    write-capacity-units = 1
  }

  ses {
    from-address = "no-reply@pcpitman.com"
    default-validation-url-base = "https://auth.pcpitman.com/validate-email"
  }

  redis {
    uri = "redis://localhost:6379"
  }

  session {
    ttl-seconds = 86400
  }
}

atlas.pekko {
  api-endpoints = [
    "com.netflix.atlas.pekko.ConfigApi",
    "com.netflix.atlas.pekko.HealthcheckApi",
    "com.pcpitman.auth.AuthApi"
  ]
}
